index:
  path: /
  defaults: { _controller: 'App\Controller\Index\IndexController::index' }

# Utilisation du RedirectController
accueil:
  path: /accueil
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: index
    permanent: true

authentication_token:
  path: /api/login
  methods: ['POST']

